/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FarmerRouteImport } from './routes/farmer'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as EquipmentIndexRouteImport } from './routes/equipment.index'
import { Route as EquipmentEquipmentIdRouteImport } from './routes/equipment.$equipmentId'
import { Route as FarmerIndexRouteImport } from './routes/farmer.index'
import { Route as FarmerPaymentsRouteImport } from './routes/farmer.payments'
import { Route as FarmerWishlistRouteImport } from './routes/farmer.wishlist'
import { Route as FarmerBookingsIndexRouteImport } from './routes/farmer.bookings.index'
import { Route as FarmerBookingsBookingIdRouteImport } from './routes/farmer.bookings.$bookingId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmerRoute = FarmerRouteImport.update({
  id: '/farmer',
  path: '/farmer',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipmentIndexRoute = EquipmentIndexRouteImport.update({
  id: '/equipment/',
  path: '/equipment/',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipmentEquipmentIdRoute = EquipmentEquipmentIdRouteImport.update({
  id: '/equipment/$equipmentId',
  path: '/equipment/$equipmentId',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmerIndexRoute = FarmerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FarmerRoute,
} as any)
const FarmerPaymentsRoute = FarmerPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => FarmerRoute,
} as any)
const FarmerWishlistRoute = FarmerWishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => FarmerRoute,
} as any)
const FarmerBookingsIndexRoute = FarmerBookingsIndexRouteImport.update({
  id: '/bookings/',
  path: '/bookings/',
  getParentRoute: () => FarmerRoute,
} as any)
const FarmerBookingsBookingIdRoute = FarmerBookingsBookingIdRouteImport.update({
  id: '/bookings/$bookingId',
  path: '/bookings/$bookingId',
  getParentRoute: () => FarmerRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/farmer': typeof FarmerRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/equipment/$equipmentId': typeof EquipmentEquipmentIdRoute
  '/farmer/payments': typeof FarmerPaymentsRoute
  '/farmer/wishlist': typeof FarmerWishlistRoute
  '/equipment/': typeof EquipmentIndexRoute
  '/farmer/': typeof FarmerIndexRoute
  '/farmer/bookings/$bookingId': typeof FarmerBookingsBookingIdRoute
  '/farmer/bookings/': typeof FarmerBookingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/equipment/$equipmentId': typeof EquipmentEquipmentIdRoute
  '/farmer/payments': typeof FarmerPaymentsRoute
  '/farmer/wishlist': typeof FarmerWishlistRoute
  '/equipment': typeof EquipmentIndexRoute
  '/farmer': typeof FarmerIndexRoute
  '/farmer/bookings/$bookingId': typeof FarmerBookingsBookingIdRoute
  '/farmer/bookings': typeof FarmerBookingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/farmer': typeof FarmerRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/equipment/$equipmentId': typeof EquipmentEquipmentIdRoute
  '/farmer/payments': typeof FarmerPaymentsRoute
  '/farmer/wishlist': typeof FarmerWishlistRoute
  '/equipment/': typeof EquipmentIndexRoute
  '/farmer/': typeof FarmerIndexRoute
  '/farmer/bookings/$bookingId': typeof FarmerBookingsBookingIdRoute
  '/farmer/bookings/': typeof FarmerBookingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/farmer'
    | '/login'
    | '/register'
    | '/equipment/$equipmentId'
    | '/farmer/payments'
    | '/farmer/wishlist'
    | '/equipment/'
    | '/farmer/'
    | '/farmer/bookings/$bookingId'
    | '/farmer/bookings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/equipment/$equipmentId'
    | '/farmer/payments'
    | '/farmer/wishlist'
    | '/equipment'
    | '/farmer'
    | '/farmer/bookings/$bookingId'
    | '/farmer/bookings'
  id:
    | '__root__'
    | '/'
    | '/farmer'
    | '/login'
    | '/register'
    | '/equipment/$equipmentId'
    | '/farmer/payments'
    | '/farmer/wishlist'
    | '/equipment/'
    | '/farmer/'
    | '/farmer/bookings/$bookingId'
    | '/farmer/bookings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FarmerRoute: typeof FarmerRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  EquipmentEquipmentIdRoute: typeof EquipmentEquipmentIdRoute
  EquipmentIndexRoute: typeof EquipmentIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farmer': {
      id: '/farmer'
      path: '/farmer'
      fullPath: '/farmer'
      preLoaderRoute: typeof FarmerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipment/': {
      id: '/equipment/'
      path: '/equipment'
      fullPath: '/equipment/'
      preLoaderRoute: typeof EquipmentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipment/$equipmentId': {
      id: '/equipment/$equipmentId'
      path: '/equipment/$equipmentId'
      fullPath: '/equipment/$equipmentId'
      preLoaderRoute: typeof EquipmentEquipmentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farmer/': {
      id: '/farmer/'
      path: '/'
      fullPath: '/farmer/'
      preLoaderRoute: typeof FarmerIndexRouteImport
      parentRoute: typeof FarmerRoute
    }
    '/farmer/payments': {
      id: '/farmer/payments'
      path: '/payments'
      fullPath: '/farmer/payments'
      preLoaderRoute: typeof FarmerPaymentsRouteImport
      parentRoute: typeof FarmerRoute
    }
    '/farmer/wishlist': {
      id: '/farmer/wishlist'
      path: '/wishlist'
      fullPath: '/farmer/wishlist'
      preLoaderRoute: typeof FarmerWishlistRouteImport
      parentRoute: typeof FarmerRoute
    }
    '/farmer/bookings/': {
      id: '/farmer/bookings/'
      path: '/bookings'
      fullPath: '/farmer/bookings/'
      preLoaderRoute: typeof FarmerBookingsIndexRouteImport
      parentRoute: typeof FarmerRoute
    }
    '/farmer/bookings/$bookingId': {
      id: '/farmer/bookings/$bookingId'
      path: '/bookings/$bookingId'
      fullPath: '/farmer/bookings/$bookingId'
      preLoaderRoute: typeof FarmerBookingsBookingIdRouteImport
      parentRoute: typeof FarmerRoute
    }
  }
}

interface FarmerRouteChildren {
  FarmerPaymentsRoute: typeof FarmerPaymentsRoute
  FarmerWishlistRoute: typeof FarmerWishlistRoute
  FarmerIndexRoute: typeof FarmerIndexRoute
  FarmerBookingsBookingIdRoute: typeof FarmerBookingsBookingIdRoute
  FarmerBookingsIndexRoute: typeof FarmerBookingsIndexRoute
}

const FarmerRouteChildren: FarmerRouteChildren = {
  FarmerPaymentsRoute: FarmerPaymentsRoute,
  FarmerWishlistRoute: FarmerWishlistRoute,
  FarmerIndexRoute: FarmerIndexRoute,
  FarmerBookingsBookingIdRoute: FarmerBookingsBookingIdRoute,
  FarmerBookingsIndexRoute: FarmerBookingsIndexRoute,
}

const FarmerRouteWithChildren =
  FarmerRoute._addFileChildren(FarmerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FarmerRoute: FarmerRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  EquipmentEquipmentIdRoute: EquipmentEquipmentIdRoute,
  EquipmentIndexRoute: EquipmentIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
